### PR TITLE
Update .travis.yml with python and django versions

### PR DESCRIPTION
**Pull request by bulv1ne**
Thought it might be best to keep travis.yml up to date with the latest python and django versions

### CODE REVIEW

**Comment by Koed00** [comment]
I made the exact same commit minute ago ;)

**Comment by bulv1ne** [comment]
Haha, closing this pull request then 😄

**Comment by Koed00** [comment]
I'm omitting DJANGO=1.9.8 cause it's deprecated.
I have a little time today, cause of holiday. Let's see if we can get everything up to date.

**Comment by bulv1ne** [comment]
It would be awesome to get a new version out from django-q. Thanks for the fast response time!

**Pull request closed without merging**
