### PR TITLE
All schedules are in UTC ignoring TIME_ZONE Settings.

### PR DESCRIPTION
**Pull request by MathiasKowoll**
I force checking TIME_ZONE settings for scheduling options as they are used in UTC instead of TIME_ZONE Settings

### CODE REVIEW

**Comment by MathiasKowoll** [comment]
Please check this functionality and let mi know

**Comment by Koed00** [comment]
Could you explain the problem you're trying to fix a little bit more?  
It is per Django guidelines that all internal times are in UTC to prevent problems with timezone aware applications. Comparing datetimes is not affected by the timezone they are in, the comparison is always done after conversion.

**Comment by MathiasKowoll** [comment]
When using Cron schedule, it next runtime is based on utc. not GMT -3. For example if I schedule to be run at 4:00 am GTM-3, it get schedule at 1:00 am GMT-3, because when it gets schedule coverts 4:00 am GMT-3 into 4:00 UTC and therefore when it gets schedule on next runtime it gets schedule at 1:00 am GMT -3

**Comment by MathiasKowoll** [comment]
I think it is related to croniter, we need to pass current datetime, as you said we don't need to change Django timezone for select jobs to be run

**Comment by MathiasKowoll** [comment]
@Koed00 did you understood the problem or need more info?

**Comment by MathiasKowoll** [comment]
This #520  should be sufficient so closing this PR

**Pull request closed without merging**
