### PR TITLE
Django 2 compatiblity

### PR DESCRIPTION
**Pull request by Eagllus**
This is not a new branch I just merged master to see if that fixes most of the Django 2.0 problems.

And I was unable to run the tests local so decided to create a PR. ~that just checks if master + django_2_compat is 👍!~

Edit 1: Well `master` + `django_2_compat` din't solve all problems.
Edit 2: Fixed a few of the bugs so far.

### CODE REVIEW

**Comment by Koed00** [comment]
Yeah, quite a lot of the tests are failing on Django 2.0, even though they ran fine in the alpha and beta stages.

I wish I had more time for it, but I just started a new job and I need to move by the end of the month.
Will try to find some time in the upcoming weekend.

**Comment by Eagllus** [comment]
@Koed00 no worries I have time to figure this out!
I hope to get somewhere with the tests this week.

**Comment by Eagllus** [comment]
ps: Enjoy your new job 😉

**Comment by Eagllus** [comment]
Closed it by mistake and it din't want me to open it but now it does XD

**Comment by Eagllus** [comment]
@Koed00 I'm kind of stuck here.

I found a way to fix the remaining problems (there all related to one thing)
The change that are made in `django.core.signing` and triggers effects that I can't seem to understand.

I added a commit showing the 'old' core.signing features working, hope you have time this weekend and that that it will save you some time.

**Comment by Eagllus** [comment]
@Koed00 any update about the problem my pr was/is experiencing?

**Comment by Koed00** [comment]
I've not had time to look into this yet. Just moved all my belongings into storage and found a temporary apartment.  Making this a priority for the weekend. I need it to work reliably with Django 2 for a new project as well. Thanks for all the work you put in Ronald. Best wishes for the new year!

**Comment by Eagllus** [comment]
@Koed00 no problem at all 😄 
I use `Django-Q` daily in production so I don't mind working on it.
Best wishes to you for the new year, with a hope nice challenges 😉

**Pull request merged**
