### PR TITLE
fixed ImportError to work with Django-2.0

### PR DESCRIPTION
**Pull request by ramashishb**

### CODE REVIEW

**Comment by Koed00** [comment]
Is that really all it takes to be 2.0 compatible?

**Comment by ramashishb** [comment]
Am testing it. Please ignore it for now.

**Comment by evgenymarkov** [comment]
So, Django 2.0 released. Is there any progress? Is there any blockers else besides importing resolve function?

**Comment by Koed00** [comment]
Not sure. I'll spend some time this week to go over the code.
But with Django 2.0, support for Python 2.7 has been dropped.
This opens up access to some more advanced multiprocessing function in python 3.4+.

But let's focus on making it work first. I'll remove all the backwards compatibility code in a later release.

@ramashishb How are you getting on with this?  Can I merge it?

**Comment by ramashishb** [comment]
Hi,

The import changes made it working with Django 2.0. However, I didn't test
it comprehensively and for now I have moved back to Django 1.11.

Ramashish

**Comment by Koed00** [comment]
Closing this cause I merged another pull request that covered this and more

**Comment by ramashishb** [comment]
Sounds good.

**Pull request closed without merging**
