### PR TITLE
[CI] Add support of python 3.6

### PR DESCRIPTION
**Pull request by Djailla**

### CODE REVIEW

**Comment by Koed00** [comment]
Is there a particular reason you need 3.6 support on the CI? 
I always try to support at most the last two versions when it comes to testing new code.

**Comment by Djailla** [comment]
@Koed00 I would say that if you mention that it's compatible with 3.6, it should be tested.

Especially when requirements will start to deprecate 3.6

**Comment by Koed00** [comment]
I actually changed the docs a few weeks back, only the pypi package still references 3.6 support. Which will be true until the next release. With 3.9 coming in October, I am trying to discourage new development against 3.6.

**Comment by Djailla** [comment]
Agreed

**Pull request closed without merging**
