### PR TITLE
update python and django versions on travis

### PR DESCRIPTION
**Pull request by monty5811**
Update travis config:

 - add python 3.5
 - add python 3.6-dev
 - update to latest Django (1.10.3)

### CODE REVIEW

**Comment by Koed00** [comment]
Python 3.5 is fine to add. But I would replace 3.4 for it.

Also Django 1.10.* does not support Python 3.6. This support doesn't happen until 1.11
Testing for it now would be a little early.

**Comment by monty5811** [comment]
That all makes sense, shall I open a new PR or force push to this one?

**Comment by Koed00** [comment]
If could push the changes on this commit, that would be great.

**Comment by monty5811** [comment]
Gonna close this in favour of a different PR.

**Pull request closed without merging**
