### PR TITLE
Close broker connection if unusable

### PR DESCRIPTION
**Pull request by Urth**
If the broker is not usable the guard loop can enter a infinite loop
where it tries to save the status every 0.5 seconds. This change forces
the broker connection to reset for those that support it.

### CODE REVIEW

**Comment by Koed00** [comment]
Cool. That will definitely solve some of the problems.
Will you be able to update the tests too? It could be a while until I get to that.

**Comment by Urth** [comment]
I'm having a stab at the tests but I'm having some difficulty with the suite so it'll take me some time.

**Comment by Urth** [comment]
I've updated the pull request with tests. I'm not sure why the aws and ironmq tests are skipped but I assume that's out of my control.

**Comment by Urth** [comment]
I forgot to say I have not implemented a close for the ORM broker because I wasn't sure if and how to handle atomic blocks. For the ORM close is a noop so the existing behaviour will stay the same.

**Pull request closed without merging**
