### PR TITLE
Replaces async occurrences with alternatives

### PR DESCRIPTION
**Pull request by P-EB**
* async is now a reserved word in python3.7
 * Rename async function to enqueue
 * Rename all async_ functions to enqueue_
 * Rename Async class to AsyncTask
 * Updates the docs.

### CODE REVIEW

**Comment by P-EB** [comment]
@Koed00 here!

**Comment by P-EB** [comment]
@Koed00 did you get some time to review these changes? Especially, the change of the naming convention, as it's an API change.

**Comment by aleksihakli** [comment]
@Koed00 it would be awesome to have this available on PyPI as a lot of projects (including ours) are currently upgrading to the new Python 3.7 release.

**Comment by doko42** [comment]
any advice, how upstream will rename the module?

**Comment by P-EB** [comment]
@doko42 what module? Did I miss a filename in my patch? :/

**Comment by doko42** [comment]
no, I'd just like to see an approval / integration of this patch before pulling it into any distro package.

**Comment by P-EB** [comment]
I agree, I'll delay until @Koed00 is there and answers :)

**Comment by Koed00** [comment]
Sorry everyone. Between holidays and my job , it's been hard to put some time in this.

I did review the code and it's all good, except that I just didn't like the word 'enqueue'.
But seeing your renaming of `Async` to `AsyncTask`, I felt that this was mnemonically better.
So I'll merge it and then rename all `enqueue_` to `async_task_`, since you did all the work.

**Comment by P-EB** [comment]
Sure, I'm fine with this. :)

I'll wait for your next release before releasing into debian.

**Pull request merged**
