### PR TITLE
Fixes #314 - Convert func to its import path str so that resubmitting failed task works

### LINKED ISSUE #314: Not enough values to unpack (expected 2, got 1)
Hello! 
I faced with this problem when I try to run command **python manage.py qcluster**:
```
[Q] INFO Q Cluster-21177 starting.
[Q] INFO Process-1:1 ready for work at 21181
[Q] INFO Process-1:2 ready for work at 21182
[Q] INFO Process-1:3 ready for work at 21183
[Q] INFO Process-1:4 ready for work at 21184
[Q] INFO Process-1:5 monitoring at 21185
[Q] INFO Process-1 guarding cluster at 21180
[Q] INFO Process-1:6 pushing tasks at 21186
[Q] INFO Q Cluster-21177 running.
[Q] INFO Enqueued 2
[Q] INFO Process-1 created a task from schedule [check_achievements_monthly]
[Q] INFO Process-1:1 processing [two-nineteen-may-pasta]
[Q] ERROR Failed [two-nineteen-may-pasta] - not enough values to unpack (expected 2, got 1)
```

I use Python 3.7, Django 2.0.7
```
from datetime import datetime
from django.contrib.auth.models import User
from django_q.tasks import schedule
from pytz import timezone

from achievements.models import Achievement, UserAchievement


def check_ach(*args, **kwargs):
    for achievement in Achievement.objects.filter(period=args[0]):
        for user in User.objects.all():
            try:
                user_achievement = achievement.users_achievements.get(user=user)
            except UserAchievement.DoesNotExist:
                user_achievement = None

            if user_achievement and user_achievement.max_amount_reached:
                continue  # user already has maximal amount of that achievement - skip

            if achievement.is_earned(user):
                UserAchievement.objects.create(achievement=achievement, user=user)


schedule(check_ach,'MONTHLY', name='check_achievements_monthly', schedule_type='M', next_run=datetime.now().astimezone(timezone('Europe/Kiev')))
```
Can you help me with this issue?

### PR DESCRIPTION
**Pull request by kennyhei**
If `async_task` is given function as a function type and not string type and task fails, resubmitting failed task doesn't work. It results in error message:

```
Not enough values to unpack (expected 2, got 1)
```

This is because `func` is stored as a string in the database and string representation of an actual function is something like `<function example at 0x01234567>`, meaning that this part in the worker fails:

```python
# if it's not an instance try to get it from the string
if not callable(task["func"]):
    try:
        module, func = f.rsplit(".", 1) # <-- FAILS HERE
        m = importlib.import_module(module)
        f = getattr(m, func)
    except (ValueError, ImportError, AttributeError) as e:
        result = (e, False)
        if error_reporter:
            error_reporter.report()
```

In our project I have solved this by creating a wrapper for `async_task`, it looks like this:

```python
from django_q.tasks import async_task as _async_task

def async_task(func, *args, **kwargs):
    # NOTE: Resubmitting failed task does not work, this is meant
    # to fix it by giving import path str as an argument instead of
    # function instance. For more information see:
    # https://github.com/Koed00/django-q/issues/314
    if isinstance(func, str):
        return _async_task(func, *args, **kwargs)
    return _async_task(f'{func.__module__}.{func.__name__}', *args, **kwargs)
```

Figured that I could just apply this fix directly in `async_task` 🙂 Works for `AsyncTask` class as well since its `run` method calls `async_task`.

Example:
```python
>>> from utilities.tasks import async_task
>>> func = async_task
>>> func = f"{func.__module__}.{func.__name__}"
>>> func
'utilities.tasks.async_task'
>>>
>>> from utilities import hello
>>> func = hello
>>> func = f"{func.__module__}.{func.__name__}"
>>> func
'utilities.hello'
```

### CODE REVIEW

**Comment by kennyhei** [comment]
Another option is to do the conversion in `save_task` because otherwise callable -check in worker becomes unnecessary.

```python
func = task["func"]
if not isinstance(func, str):
    func = f"{func.__module__}.{func.__name__}"
Task.objects.create(
    id=task["id"],
    name=task["name"],
    func=func,
    hook=task.get("hook"),
    args=task["args"],
    kwargs=task["kwargs"],
    started=task["started"],
    stopped=task["stopped"],
    result=task["result"],
    group=task.get("group"),
    success=task["success"],
    attempt_count=1
)
```

**Comment by Koed00** [comment]
The latter seems the nicer solution. If you agree, could you update the pr?

**Comment by kennyhei** [comment]
Updated ✅

**Comment by kennyhei** [comment]
Just noticed this doesn't work e.g. for class methods. Need to refine a bit.

**Comment by kennyhei** [comment]
Had to make bigger changes but now classmethods work as well. Example:

```python
>>> from django_q_monitor.messages import FailedTasksSlack
>>> func = FailedTasksSlack._dispatch # this is inherited classmethod
>>> func = f'{func.__self__.__module__}.{func.__self__.__name__}.{func.__name__}'
>>> func
'django_q_monitor.messages.FailedTasksSlack._dispatch'
>>> import inspect, pydoc
>>> inspect.ismethod(FailedTasksSlack._dispatch)
True
>>> pydoc.locate(func)
<bound method Message._dispatch of <class 'django_q_monitor.messages.FailedTasksSlack'>>
>>>
>>> from utlities.tasks import async_task
>>> from utilities.tasks import async_task
>>> inspect.isfunction(async_task)
True
>>> func = async_task
>>> func = f"{func.__module__}.{func.__name__}"
>>> func
'utilities.tasks.async_task'
>>> pydoc.locate(func)
<function async_task at 0x1128c33a0>
>>> 
```

`pydoc.locate` returns `None` if it cannot locate anything from given string, removed `try-except`.

**Review by Koed00 — APPROVED** [review]

**Pull request merged**
