### PR TITLE
update django versions in CI config

### PR DESCRIPTION
**Pull request by monty5811**
Hi,

Thought it would be good to update the Django versions 😄 

- Update Django 1.10 from rc to 1.10.6
- Add 1.11rc1

### CODE REVIEW

**Comment by Eagllus** [comment]
I think testing 1.11rc1 is a bit to much it's still very heavy under development

**Comment by monty5811** [comment]
This post on the mailing list seems to say it is nearly ready to go: https://groups.google.com/forum/#!topic/django-developers/j4KxWRLXUdo,

Maybe I have missed something?

Also, since testing on 1.10 was done on the RC, I thought it would be fine.

**Comment by Eagllus** [comment]
@monty5811 your right I thought rc1 was the still heavy under development.
Will you also fix the problem for the tests? or would you like me to have a look at it?

**Comment by monty5811** [comment]
It looks like the issue is in [`__init__.py`](https://github.com/Koed00/django-q/blob/master/django_q/__init__.py#L16) - the imports to allow the root imports.

I think removing those fixes the issues.

The file already says they are scheduled for deprecation. A quick [search](https://github.com/search?q=%22from+django_q+import+async%22&type=Code&utf8=%E2%9C%93) shows only two projects using these imports. Maybe it is time to remove them?

**Comment by danielwelch** [comment]
@monty5811 If for whatever reason that isn't ready to be deprecated, you could just expand the check [here](https://github.com/Koed00/django-q/blob/master/django_q/__init__.py#L15) to include django version 1.11. Doing so at least fixes the current error.

**Comment by monty5811** [comment]
Thanks @danielwelch - I hadn't noticed what that line was doing. I've added another check for `1.11*`. Though that if statement is looking kind of long now...

**Comment by Koed00** [comment]
I've merged parts of this and used some code from other similar commits. 
Thanks for contributing, it is appreciated.

**Pull request closed without merging**
