### PR TITLE
Adding tracebacks to the error logs and saved failed tasks

### PR DESCRIPTION
**Pull request by strets123**
I found the tasks difficult to debug, perhaps this is just a configurational issue on my side but I believe using traceback produces a more useful output.

### CODE REVIEW

**Comment by gabor-boros** [comment]
👍 Really like the idea

**Comment by thinkwelltwd** [comment]
strets123, just curious why you closed this? 

Koed00, just curious why it wasn't merged. I've also found this PR very helpful on jobs that crash.

**Comment by strets123** [comment]
Ah sotry was nust tidying up and was so long ago i had forgotten what i was even using this for. I need to add test coverage and did not at the time know how to test logs. Happy to reopen.

**Comment by Koed00** [comment]
merged through bd062503c5be50d7b9170834899defd92b81dbee

**Pull request closed without merging**
