### PR TITLE
added long polling support 

### PR DESCRIPTION
**Pull request by Javedgouri**
introduce new parameter in broker sqs block
parameter for long polling is receive_message_wait_time_seconds

eg :
Q_CLUSTER = {
      'name': 'test-queue',
      'sqs': {
         'aws_region': AWS_S3_REGION_NAME,
         'aws_access_key_id': AWS_ACCESS_KEY_ID,
         'aws_secret_access_key': AWS_SECRET_ACCESS_KEY,
         'receive_message_wait_time_seconds':20
     }
}

### CODE REVIEW

**Comment by Koed00** [comment]
Before I can merge this it needs to be covered in the tests. Just adding the new receive_message_wait_time_seconds parameter would probably fix the coverage. Would also be great if you can add this parameter to the docs.  
Thanks for your addition!

**Comment by Javedgouri** [comment]
receive_message_wait_time_seconds  in which file i have to add this parameter for coverage.

**Comment by Koed00** [comment]
Just find the `canceled_sqs` tests in the `tests/test_brokers.py`
If you add the parameter in one of the sqs task calls, it should be covered.

Let me know if you are having issues with this.

**Review by Koed00 — APPROVED** [review]

**Comment by Koed00** [comment]
Thanks a lot for taking the time to do this.

**Comment by Javedgouri** [comment]
@NigelSwinson  i have created a pull request for this issue

**Pull request merged**
