### PR TITLE
Temporary fix for circular imports in tasks.py

### PR DESCRIPTION
**Pull request by codeSamuraii**
Temporary fix for circular imports in `tasks.py`. (https://github.com/Koed00/django-q/issues/331).

Not very clean but will do the job before a fix comes out.

### CODE REVIEW

**Comment by lamby** [comment]
I suggest you actually *move* the original line and put it inline within the `def _sync(pack)` method, ie. 

```python
def _sync(pack):
    """Simulate a package travelling through the cluster."""
    from django_q.cluster import worker, monitor
    task_queue = Queue()
```

Star imports kinda suck, after all.

**Comment by codeSamuraii** [comment]
> Star imports kinda suck, after all.

Indeed!

This was meant to be a quick (and dirty) fix until someone found a better solution.
Maybe you can submit a PR with your solution?

**Comment by lamby** [comment]
@codeSamuraii Sure thing; submitted as https://github.com/Koed00/django-q/pull/356

**Comment by codeSamuraii** [comment]
Closed because of #356 better solution.

**Pull request closed without merging**
