### PR TITLE
Change schedule function to update or create new

### PR DESCRIPTION
**Pull request by Eagllus**
By searching for the function we can update existing schedules.

During development I noticed every time I changed a param from my scheduled function
there was a entry inserted into the database. Giving me multiple scheduled functions from a single
function.

I havent updated any tests, if you want I can add a test for this 'new' feature

### CODE REVIEW

**Comment by Eagllus** [comment]
Cant seem to run the tests locally (not sure why)

**Comment by Koed00** [comment]
Did you install py-test and pytest-django ?

**Comment by Eagllus** [comment]
Both are installed correctly and when I run
```
python runtests.py
========================================================= test session starts =========================================================
platform darwin -- Python 3.5.0, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
django settings: django_q.tests.settings (from ini file)
rootdir: /Users/ronald/Git/django-q, inifile: pytest.ini
plugins: django-2.9.1
collected 28 items

django_q/tests/test_admin.py .
django_q/tests/test_brokers.py ..FssFF
django_q/tests/test_cached.py F...
django_q/tests/test_cluster.py ....FF..FF
django_q/tests/test_commands.py ...
django_q/tests/test_monitor.py ..
django_q/tests/test_scheduler.py F
```

seems most of the errors are from
```
    def qsize(self):
        # Raises NotImplementedError on Mac OSX because of broken sem_getvalue()
>       return self._maxsize - self._sem._semlock._get_value()
E       NotImplementedError
```

so that makes it very difficult for me to test

**Comment by Eagllus** [comment]
Localy my test_scheduler fails for before travis doest
```
___________________________________________________________ test_scheduler ____________________________________________________________

broker = <brokers.redis_broker.Redis object at 0x105145d30>

    @pytest.mark.django_db
    def test_scheduler(broker):
        broker.list_key = 'scheduler_test:q'
        broker.delete_queue()
        schedule = create_schedule('math.copysign',
                                   1, -1,
                                   name='test math',
                                   hook='django_q.tests.tasks.result',
                                   schedule_type=Schedule.HOURLY,
                                   repeats=1)
        assert schedule.last_run() is None
        # run scheduler
        scheduler(broker=broker)
        # set up the workflow
        task_queue = Queue()
        stop_event = Event()
        stop_event.set()
        # push it
        pusher(task_queue, stop_event, broker=broker)
>       assert task_queue.qsize() == 1

django_q/tests/test_scheduler.py:44:
```

**Comment by Koed00** [comment]
I will have a closer look at it later. Can't tell what's happening without running your pull request.

**Comment by Eagllus** [comment]
Sure, it's not a blocking problem or anything.
Just thought safe you some work on fixing this.

**Comment by Koed00** [comment]
Finally had time to look it over. You're using the `func` as the key for the update or create. Since the tests all use the same `func`, you end up with one updated schedule instead of a bunch of separate ones and the tests fail. I think using the `name` as the update key will fix this, but since the `name` is optional we'll run into troubles there. So we'll probably have to supply a default `name` with a uuid or tag.

On a side note. I prefer returning the [0] zero index on the update_or_create tuple instead of assigning it to _ since that might clash with translations.

**Comment by Eagllus** [comment]
Updated the return [0] zero index.
Any idea about the func params? It's the only param that is really required.

**Comment by Eagllus** [comment]
@Koed00 did you had time to think about a solution for this problem?

**Comment by Eagllus** [comment]
@Koed00 I think we can close this one?

**Comment by Koed00** [comment]
@Eagllus Yeah. I added a check for duplicate schedules at some point in d39868534594488492bf0aa61ea7bca727dd6d0d . Thanks for spotting this.

**Comment by Eagllus** [comment]
Your very welcome, love the application :)

**Pull request closed without merging**
